name: Publish NPM

on:
  push:
    branches: [ master, beta, alpha ]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    name: Publish NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Publish Package to NPM
        run: |
          npm i -g pnpm @semantic-release/changelog @semantic-release/git semantic-release
          pnpm i --frozen-lockfile
          semantic-release
